### ISSUE TITLE
Any idea what the "Do Not Disturb" setting actually does?

### ISSUE THREAD

**Issue by jondthompson** [jnewland/mpr-6zhmaut-api#16]
I know this is more about the device itself, but given the documentation only mentions this setting in the API, I thought someone this project's community might already have figured out what it does...

**Comment by cbschuld-wix** [comment]
Hi @jondthompson - My understanding of the "Do Not Disturb" function is that it is simply mute.  Transparently I have not ever called it nor used it on my amps so I am not 100% sure what it does.  But I think it's simply mute.

**Comment by jondthompson** [comment]
So there's actually two mute options? Strange. I wonder what the difference is.

 I was thinking that it might be some sort of security lock more than a mute.
