### ISSUE TITLE
Multiple amps cause odd return when querying nonexistent

### ISSUE THREAD

**Issue by cbschuld** [jnewland/mpr-6zhmaut-api#2]
in my case I have two amps in series: master & slave 1

when querying a non-existent amp (>30\r) I receive a set of odd bytes on the receive line that are intermixed into the payload from the previous commands for amp one and amp two

I believe the fix is to environmentally set what your amp count is and react to that by not querying non existent amps.  Related, the error never happens on the first amp, ONLY the second amp.  I re-wired my amps by swapping their roles and the error maintained.  As soon as I stopped querying amp 3 it worked great.

Also, I removed amp number two and left the code unchanged and it worked great.  It only appears to be an issue on a two amp system when querying for three.

I'll submit a PR to deal with this.

@jnewland - **great** work on this; I love the encapsulation in node, makes it so easy to deal with on the PI

**Comment by jnewland** [comment]
> I'll submit a PR to deal with this.

Nice, thank you! I don't have another amp to test on but I'll be happy to review the PR and test it against my setup. 👍 

> @jnewland - great work on this; I love the encapsulation in node, makes it so easy to deal with on the PI

😊 Thanks! Raspberry Pis sure are great for 'decorating' hardware with a slightly better interface when necessary. 👍

**Comment by cbschuld** [comment]
@jnewland my changes didn't stick, resubmitting the PR

**Comment by jnewland** [comment]
Fixed in https://github.com/jnewland/mpr-6zhmaut-api/pull/6.
