### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by dk253** [jnewland/mpr-6zhmaut-api#7]
I have not tried your code but I am so happy you did this.  I just bought two of these amps and was wondering if I was stuck with the wall interfaces or whether I could control them with my phone.  This is the piece I was missing.

Two questions:

1. what kind of wire did you get?  I am assuming a usb to serial, but did you have to create your own or is there an off-the-shelf?
2. If I have two amps set up in a master/slave config, do I need to connect to both serial ports or just the master?

Thanks!

**Comment by cbschuld** [comment]
@dk253 - I have the same setup; I have a bit of my discovery process documented as well - https://chrisschuld.com/2019/05/whole-house-audio/

Here is how I would answer your questions (very delayed but just noticed them)

1. I chose to run 14AWG
2. you would connect only one to the "master" and make sure you have the ribbon cable running between them

**Comment by cbschuld** [comment]
does not really address an issue; going to close it out.  @dk253 if you bump into questions you are welcome to reach out to me via email - hit the web url ^ and contact me
